version: '2.4'

services:

  gateway:
    build: frontend/
    restart: always
    ports:
      - 80:80

  backend:
    build: backend/
    restart: always
    depends_on:
      - postgres
      - gateway

  postgres:
    build: postgres/
    restart: always
    environment:
      POSTGRES_PASSWORD: verysecurepassword123
    volumes:
      - v-postgres:/var/lib/postgresql/data
    ports:
        - 5432:5432

  agent:
    build: agent/
    restart: always
    privileged: true
    depends_on:
      - postgres
      - backend

volumes:
  v-postgres:
