version: '2.4'

services:

  gateway:
    build: frontend/
    restart: always
    ports:
      - 80:80

  backend:
    build: backend/
    restart: always
    depends_on:
      - postgres
      - gateway

  agent:
    build: agent/
    restart: always
    privileged: true
    depends_on:
      - postgres
      - backend
