runtime: python37

entrypoint: gunicorn -b :$PORT --worker-class eventlet -w 1 'src:create_app()'

instance_class: F4

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  DB_HOST: 35.187.229.186
  DB_USER: alarmyuser
  DB_PASSWORD: 'Gns9ybDC3X3jfpkbeazAe89w7W'
  DB_NAME: alarmy
  JWT_SECRET_KEY: 'myjwtsecretkey'
  SENDGRID_API_KEY: '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'
  PROJECT_ID: 'iot-ca2-265007'
  REGION: 'asia-east1'
  REGISTRY_ID: 'CA2-Registry'
