"""empty message

Revision ID: f8c97b061b16
Revises: baeeb61276f1
Create Date: 2019-12-30 02:09:20.964502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8c97b061b16'
down_revision = 'baeeb61276f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_alert',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('gas_ticker', sa.BigInteger(), nullable=False),
    sa.Column('temp_ticker', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['gas_ticker'], ['gas.ticker'], ),
    sa.ForeignKeyConstraint(['temp_ticker'], ['temperature.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gas_alert')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_table('gas_alert',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('alert_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('gas_ticker', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('temp_ticker', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gas_ticker'], ['gas.ticker'], name='gas_alert_gas_ticker_fkey'),
    sa.ForeignKeyConstraint(['temp_ticker'], ['temperature.ticker'], name='gas_alert_temp_ticker_fkey'),
    sa.PrimaryKeyConstraint('id', name='gas_alert_pkey')
    )
    op.drop_table('env_alert')
    # ### end Alembic commands ###
