"""empty message

Revision ID: 13e9fcf3fd01
Revises: dd3efdc7d646
Create Date: 2020-01-04 14:11:40.608916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e9fcf3fd01'
down_revision = 'dd3efdc7d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'id', autoincrement=True, nullable=False, new_column_name='cid')
    op.alter_column('env_alert', 'id', autoincrement=True, nullable=False, new_column_name='cid')
    op.alter_column('person_alert', 'id', autoincrement=True, nullable=False, new_column_name='cid')
    # op.add_column('device', sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False))
    # op.drop_column('device', 'id')
    # op.add_column('env_alert', sa.Column('cid', sa.BigInteger(), autoincrement=True, nullable=False))
    # op.drop_column('env_alert', 'id')
    # op.add_column('person_alert', sa.Column('cid', sa.BigInteger(), autoincrement=True, nullable=False))
    # op.drop_column('person_alert', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('person_alert', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # op.drop_column('person_alert', 'cid')
    # op.add_column('env_alert', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # op.drop_column('env_alert', 'cid')
    # op.add_column('device', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_column('device', 'cid')
    op.alter_column('device', 'cid', autoincrement=True, nullable=False, new_column_name='id')
    op.alter_column('env_alert', 'cid', autoincrement=True, nullable=False, new_column_name='id')
    op.alter_column('person_alert', 'cid', autoincrement=True, nullable=False, new_column_name='id')
    # ### end Alembic commands ###
