"""empty message

Revision ID: 526506c4bec9
Revises: 67296d1de19e
Create Date: 2020-01-03 21:55:48.932400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526506c4bec9'
down_revision = '67296d1de19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alarm', sa.Boolean(), nullable=False),
    sa.Column('poll_interval', sa.Integer(), nullable=False),
    sa.Column('alert_interval', sa.Integer(), nullable=False),
    sa.Column('alarm_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
