"""empty message

Revision ID: 67296d1de19e
Revises: 98281db01d69
Create Date: 2019-12-30 19:20:50.937193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67296d1de19e'
down_revision = '98281db01d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_alert',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_alert')
    # ### end Alembic commands ###
