"""empty message

Revision ID: 98281db01d69
Revises: f8c97b061b16
Create Date: 2019-12-30 14:47:22.764706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98281db01d69'
down_revision = 'f8c97b061b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('get_alerts', sa.Boolean(), nullable=False, server_default="1"))
    op.alter_column('users', 'get_alerts', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'get_alerts')
    # ### end Alembic commands ###
