"""empty message

Revision ID: baeeb61276f1
Revises: ea3954dfef0e
Create Date: 2019-12-30 01:59:31.454165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeeb61276f1'
down_revision = 'ea3954dfef0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_alert',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=False),
    sa.Column('gas_ticker', sa.BigInteger(), nullable=False),
    sa.Column('temp_ticker', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['gas_ticker'], ['gas.ticker'], ),
    sa.ForeignKeyConstraint(['temp_ticker'], ['temperature.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('gas_alert')
    # ### end Alembic commands ###
