"""empty message

Revision ID: dd3efdc7d646
Revises: 526506c4bec9
Create Date: 2020-01-03 23:43:39.710043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3efdc7d646'
down_revision = '526506c4bec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('device', sa.Column('vflip', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'vflip')
    op.drop_column('device', 'email')
    # ### end Alembic commands ###
