"""empty message

Revision ID: e738942b274b
Revises: 
Create Date: 2019-12-25 23:56:35.838854

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e738942b274b'
down_revision = None
branch_labels = None
depends_on = None


ROLES = [
    (u'admin', u'Admin'),
    (u'user', u'User')
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(ROLES), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
