"""empty message

Revision ID: ea3954dfef0e
Revises: 
Create Date: 2019-12-29 16:23:40.404654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3954dfef0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas',
    sa.Column('ticker', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lpg', sa.Float(), nullable=False),
    sa.Column('co', sa.Float(), nullable=False),
    sa.Column('smoke', sa.Float(), nullable=False),
    sa.Column('capture_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('capture_time')
    )
    op.create_table('temperature',
    sa.Column('ticker', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('capture_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('capture_time')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('temperature')
    op.drop_table('gas')
    # ### end Alembic commands ###
