"""empty message

Revision ID: fd75cc9ca20f
Revises: 2eeca843d976
Create Date: 2020-01-05 00:21:27.347478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd75cc9ca20f'
down_revision = '2eeca843d976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('detect_humans', sa.Boolean(), nullable=False, server_default="0"))
    op.alter_column('device', 'detect_humans', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'detect_humans')
    # ### end Alembic commands ###
